// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7gmnQqYfgNGfAzHhBjmUfw2PCn_QzRo',
    appId: '1:629552520417:web:aec32eb268f5da9b342ba0',
    messagingSenderId: '629552520417',
    projectId: 'fitness-app-73fa0',
    authDomain: 'fitness-app-73fa0.firebaseapp.com',
    storageBucket: 'fitness-app-73fa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiaeBPiVi2BZKb6WRjyOMRMSQkt6OSh2o',
    appId: '1:629552520417:android:10917ce3e747432b342ba0',
    messagingSenderId: '629552520417',
    projectId: 'fitness-app-73fa0',
    storageBucket: 'fitness-app-73fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6lKpnm6RfDs-oD5O9dWQdWlNzzAnqrI',
    appId: '1:629552520417:ios:0d741065f7b3f1f1342ba0',
    messagingSenderId: '629552520417',
    projectId: 'fitness-app-73fa0',
    storageBucket: 'fitness-app-73fa0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6lKpnm6RfDs-oD5O9dWQdWlNzzAnqrI',
    appId: '1:629552520417:ios:0d741065f7b3f1f1342ba0',
    messagingSenderId: '629552520417',
    projectId: 'fitness-app-73fa0',
    storageBucket: 'fitness-app-73fa0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX7gmnQqYfgNGfAzHhBjmUfw2PCn_QzRo',
    appId: '1:629552520417:web:985025665a44a4de342ba0',
    messagingSenderId: '629552520417',
    projectId: 'fitness-app-73fa0',
    authDomain: 'fitness-app-73fa0.firebaseapp.com',
    storageBucket: 'fitness-app-73fa0.firebasestorage.app',
  );
}
