/// Flutter icons CustomIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_done = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_circle = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kcl = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_tracker = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
